routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Site
Route::get('/', 'Blog\BlogController@index');
Route::get('/page/{slug}', 'Blog\BlogController@show')->name('page');
Route::resource('/blog','Articles\ArticlesController');
//Route::get('/blog/topic/{slug}', 'Articles\ArticlesController@showBySlug')->name('show-by-slug');
//Route::post('/blog/topic/{slug}', 'Articles\ArticlesController@loadBySlug')->name('show-by-slug-topic');
Route::get('/coockie-policy', 'Blog\PoliciesController@coockiePolicy')->name('coockie-policy');
Route::get('/legal-data', 'Blog\PoliciesController@legalData')->name('legal-data');
Route::post('/blog/load_data', 'Articles\ArticlesController@load_data')->name('load_data');
//Route::post('/blog/by-topic', 'Articles\ArticlesController@getByTopic')->name('by-topic');
Auth::routes();

// Auth
Route::get('/register', 'Admin\AdminController@redirect');
Route::get('/password/reset', 'Admin\AdminController@redirect');
Route::get('/admin', 'Admin\AdminController@admin');
Route::post('/submit','Blog\SendMailController@submit')->name('send-mail');
// Admin
Route::group(['middleware'=>'auth', 'prefix'=>'admin'],function () {
    Route::resource('/pages', 'Admin\PagesController');
    Route::resource('/articles', 'Admin\ArticlesController');
    Route::resource('/topics', 'Admin\TopicsController');
    Route::post('/pages/{page}/set-main-page', 'Admin\PagesController@setMainPage')->name('set-main-page');
});

app/Topic.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Topic extends Model
{
    protected $fillable = [
      'title'
    ];

    public function articles(){
        return $this->hasMany('App\Article', 'topic_id')->get();
    }
}

app/Http/Controllers/Admin/TopicsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Topic;
use Illuminate\Http\Request;

class TopicsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $topics = Topic::all();
        return view('admin.topics.index')->with('topics', $topics);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.topics.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Topic $topic)
    {
        try {
            $topic->create($request->all());
            return redirect()->route('topics.index')->with('success', 'Topic was successful created');
        }catch (\Exception $e){
            return redirect()->back()->with('error', (string)$e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $topic = Topic::find($id);
        return view('admin.topics.edit')->with('topic', $topic);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{
       $topic = Topic::where('id', $id)->first();
       $topic->update($request->all());

       return redirect()->route('topics.index')->with('success', 'Topic successful updated');
        }catch (\Exception $e){
            return redirect()->back()->with('error', (string)$e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $topic = Topic::find($id);
            $topic->delete();

            return back()->with('success', 'Topic was successful deleted');
        }catch (\Exception $e){
            return redirect()->back()->with('error', (string)$e->getMessage());
        }
    }
}

resources/views/admin/topics/create.blade.php
@extends('layouts.admin-app')

@section('content')
    <form method="post" action="{{route('topics.store')}}" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="exampleFormControlInput1">Title</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" name="title">
        </div>
        <button type="submit" class="btn btn-success">Save</button>
    </form>
@endsection

resources/views/admin/topics/edit.blade.php
@extends('layouts.admin-app')

@section('content')
    <form method="post" action="{{route('topics.update', $topic->id)}}">
        @csrf
        @method('put')
        <div class="form-group">
            <label for="exampleFormControlInput1">Title</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" name="title" value="{{$topic->title}}">
        </div>
        <button type="submit" class="btn btn-success">Save</button>
    </form>
@endsection

resources/views/admin/topics/index.blade.php
@extends('layouts.admin-app')

@section('content')
    <a href="{{route('topics.create')}}" class="btn btn-info mb-1 w-100">Create topic</a>
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Article</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach($topics as $key => $value)
        <tr>
            <th scope="row">{{$key+1}}</th>
            <td>{{$value->title}}</td>
            <td>
                <ul class="p-0">
            @foreach($value->articles() as $article)
                        <li><a href="{{route('blog.show', $article->slug)}}">{{$article->title}}</a></li>
                @endforeach
                </ul>
            </td>
            <td class="d-flex">
                <a class="btn btn-warning action-button" href="{{route('topics.edit', $value->id)}}">Edit</a>
                <form method="post" action="{{route('topics.destroy', $value->id)}}">
                    @csrf
                    @method('delete')
                    <button class="btn btn-danger action-button ml-2" type="submit">Delete</button>
                </form>
            </td>
        </tr>
            @endforeach
        </tbody>
    </table>
@endsection