routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Site
Route::get('/', 'Blog\BlogController@index');
Route::get('/page/{slug}', 'Blog\BlogController@show')->name('page');
Route::resource('/blog','Articles\ArticlesController');
//Route::get('/blog/topic/{slug}', 'Articles\ArticlesController@showBySlug')->name('show-by-slug');
//Route::post('/blog/topic/{slug}', 'Articles\ArticlesController@loadBySlug')->name('show-by-slug-topic');
Route::get('/coockie-policy', 'Blog\PoliciesController@coockiePolicy')->name('coockie-policy');
Route::get('/legal-data', 'Blog\PoliciesController@legalData')->name('legal-data');
Route::post('/blog/load_data', 'Articles\ArticlesController@load_data')->name('load_data');
//Route::post('/blog/by-topic', 'Articles\ArticlesController@getByTopic')->name('by-topic');
Auth::routes();

// Auth
Route::get('/register', 'Admin\AdminController@redirect');
Route::get('/password/reset', 'Admin\AdminController@redirect');
Route::get('/admin', 'Admin\AdminController@admin');
Route::post('/submit','Blog\SendMailController@submit')->name('send-mail');
// Admin
Route::group(['middleware'=>'auth', 'prefix'=>'admin'],function () {
    Route::resource('/pages', 'Admin\PagesController');
    Route::resource('/articles', 'Admin\ArticlesController');
    Route::resource('/topics', 'Admin\TopicsController');
    Route::post('/pages/{page}/set-main-page', 'Admin\PagesController@setMainPage')->name('set-main-page');
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'title', 'description', 'short_description', 'author', 'reading_time', 'slug', 'topic_id'
    ];

    public function topics(){
        return $this->belongsTo('App\Topic', 'topic_id')->get();
    }
}

app/Http/Controllers/Admin/ArticlesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use App\Http\Controllers\Controller;
use App\Topic;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ArticlesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::orderBy('created_at', 'desc')->get();

        return view('admin.articles.index')->with('articles', $articles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $topics = Topic::all();
        return view('admin.articles.create')->with('topics', $topics);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Article $article)
    {
        $name = Carbon::now()->toTimeString(). '_' . Carbon::now()->toDateString(). '_' .$request->image->getClientOriginalName();
        $file = $request->file('image');
        $file->move('img/articles', $name);
        $request->image = $name;
        $article->title = $request->title;
        $article->slug = $request->slug;
        $article->description = $request->description;
        $article->short_description = $request->short_description;
        $article->image = $name;
        $article->author = $request->author;
        $article->reading_time = $request->reading_time;
        $article->topic_id = $request->topic_id;
        $article->save();

        return redirect()->route('articles.index')->with('success', 'Article was created successful');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $topics = Topic::all();
        $article = Article::where('id', $id)->first();

        return view('admin.articles.edit')->with('article', $article)->with('topics', $topics);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{
        $article = Article::where('id', $id)->first();
        $old_image = $article->image;
        if (isset($request->image)){
            $name = Carbon::now()->toTimeString(). '_' . Carbon::now()->toDateString(). '_' .$request->image->getClientOriginalName();
            $file = $request->file('image');
            $file->move('img/articles', $name);
            $article->title = $request->title;
            $article->slug = $request->slug;
            $article->description = $request->description;
            $article->short_description = $request->short_description;
            $article->author = $request->author;
            $article->reading_time = $request->reading_time;
            $article->topic_id = $request->tag_id;
            $article->image = $name;
            $article->save();
            unlink(public_path('/img/articles/'.$old_image));
        } else {
            $article->update($request->all());
        }
        return redirect()->route('articles.index')->with('success', 'articles was successful updated');
        } catch (\Exception $e){
            return redirect()->back()->with('error', (string)$e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
        $article = Article::find($id);

        unlink(public_path('/img/articles/'.$article->image));
        $article->delete();

        return back()->with('success', 'Article was successful deleted');
        } catch ( \Exception $e){
            return back()->with('error', (string)$e->getMessage());
        }
    }
}

app/Http/Controllers/Articles/ArticlesController.php
<?php

namespace App\Http\Controllers\Articles;

use App\Article;
use App\Http\Controllers\Controller;
use App\Page;
use App\Topic;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use V8Js;

class ArticlesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pages = Page::where('parent_id', 0)->orderBy('created_at', 'desc')->get();
        $data = Article::orderBy('created_at', 'desc')->limit(3)->get();
        $topics = Topic::all();
        return view('blog')->with('pages', $pages)->with('data', $data)->with('topics', $topics);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $pages = Page::where('parent_id', 0)->orderBy('created_at', 'desc')->get();
        $article = Article::where('slug', $slug)->first();
        $topics = Topic::all();

        return view('single-article')->with('pages', $pages)->with('topics', $topics)->with('article', $article);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function showBySlug(){
        $pages = Page::where('parent_id', 0)->orderBy('created_at', 'desc')->get();
//        $topic_id = Topic::where('slug', $slug)->first();
//        $articles = Article::where('topic_id', $topic_id->id)->get();
        $topics = Topic::all();
        return view('topics')->with('pages', $pages)->with('topics', $topics);
    }

    public function load_data(Request $request){
        $limit = 3;
        $page = $request->page ? $request->page : 0;
        $topic = $request->topic ? $request->topic : null;
        $search = $request->search ? $request->search : '';
        if($request->ajax())
        {
            $query = Article::orderBy('created_at', 'DESC');

            if ($topic)
                $query = $query->where('topic_id', $topic);

            if ($search){

                $query = $query->where(function ($query) use ($search) {
                    return $query->where('title', 'LIKE', '%'.$search.'%')
                        ->orWhere('short_description', 'LIKE', '%'.$search.'%')
                        ->orWhere('description', 'LIKE', '%'.$search.'%');
                });
            }
            $count = $query->count();
            $pages = ceil($count / $limit);
            $offset = $limit * $page;

            $data = $query
                ->offset($offset)
                ->limit($limit)
                ->get();
            $output = '';
            if(!empty($data))
            {
//                foreach($data as $key => $value)
//                {
//                    $output .= view('components.article')->with('value', $value)->render();
//                    $last_id = $value->id;
//                }
                $output .= view('components.article')->with('data', $data)->render();
            }

            return response()->json([
                'output' => $output,
                'pages' => $pages,
                'page' => ++$page
            ]);
        }
    }

}

resources/views/admin/articles/create.blade.php
@extends('layouts.admin-app')

@section('content')
    <form method="post" action="{{route('articles.store')}}" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="exampleFormControlInput1">Title</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" name="title">
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Slug</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" name="slug">
        </div>
        <div class="form-group">
            <label for="exampleFormControlFile1">Image</label>
            <input type="file" class="form-control-file" id="exampleFormControlFile1" name="image">
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Description</label>
            <textarea class="form-control post" id="exampleFormControlTextarea1" name="description" rows="5"></textarea>
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea2">Short description</label>
            <textarea class="form-control post" id="exampleFormControlTextarea2" name="short_description" rows="5"></textarea>
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput2">Author</label>
            <input type="text" class="form-control" id="exampleFormControlInput2" name="author">
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput3">Reading time</label>
            <input type="text" class="form-control" id="exampleFormControlInput3" name="reading_time">
        </div>
        <div class="form-group">
            <label for="exampleFormControlSelect1">Topic</label>
            <select class="form-control" id="exampleFormControlSelect1" name="topic_id">
                <option value="0">None</option>
                @foreach($topics as $topic)
                <option value="{{$topic->id}}">{{$topic->title}}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-success">SAVE</button>
    </form>
@endsection

resources/views/admin/articles/edit.blade.php
@extends('layouts.admin-app')

@section('content')
    <form method="post" action="{{route('articles.update', $article->id)}}" enctype="multipart/form-data">
        @csrf
        @method('put')
        <div class="form-group">
            <label for="exampleFormControlInput1">Title</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" value="{{$article->title}}" name="title">
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Slug</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" value="{{$article->slug}}" name="slug">
        </div>
        <div class="form-group">
            <label for="exampleFormControlFile1">Image</label>
            <div>
                <label>Current image</label>
            <img class="d-block mb-2" src="/img/articles/{{$article->image}}" width="200" height="200">
            </div>
            <input type="file" class="form-control-file" id="exampleFormControlFile1" value="" name="image">
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Description</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" name="description" rows="5">{{$article->description}}</textarea>
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea2">Short description</label>
            <textarea class="form-control" id="exampleFormControlTextarea2" name="short_description" rows="5">{!! $article->short_description !!}</textarea>
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput2">Author</label>
            <input type="text" class="form-control" id="exampleFormControlInput2" name="author" value="{{$article->author}}">
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput3">Reading time</label>
            <input type="text" class="form-control" id="exampleFormControlInput3" name="reading_time" value="{{$article->reading_time}}">
        </div>
        <div class="form-group">
            <label for="exampleFormControlSelect1">Topic</label>
            {{$article->topic_id}}
            <select class="form-control" id="exampleFormControlSelect1" name="topic_id">
                <option value="0">None</option>
                @foreach($topics as $topic)
                    @if($topic->id == $article->topic_id)
                        <option value="{{$topic->id}}" selected>{{$topic->title}}</option>
                    @else
                    <option value="{{$topic->id}}">{{$topic->title}}</option>
                    @endif
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-success">SAVE</button>
    </form>
@endsection

resources/views/admin/articles/index.blade.php
@extends('layouts.admin-app')

@section('content')
    <a href="{{route('articles.create')}}" class="btn btn-info mb-1 w-100">Create article</a>
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Short description</th>
            <th scope="col">Image</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach($articles as $key => $value)
        <tr>
            <th scope="row">{{$key+1}}</th>
            <td>{{$value->title}}</td>
            <td>{!!Str::limit($value->short_description, 200)!!}</td>
            <td><img src="/img/articles/{{$value->image}}" width="100px" height="100px"></td>
            <td class="d-flex">
                <a class="btn btn-warning action-button" href="{{route('articles.edit', $value->id)}}">Edit</a>
                <form method="post" action="{{route('articles.destroy', $value->id)}}">
                    @csrf
                    @method('delete')
                    <button class="btn btn-danger action-button ml-2" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>
@endsection