routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Site
Route::get('/', 'Blog\BlogController@index');
Route::get('/page/{slug}', 'Blog\BlogController@show')->name('page');
Route::resource('/blog','Articles\ArticlesController');
//Route::get('/blog/topic/{slug}', 'Articles\ArticlesController@showBySlug')->name('show-by-slug');
//Route::post('/blog/topic/{slug}', 'Articles\ArticlesController@loadBySlug')->name('show-by-slug-topic');
Route::get('/coockie-policy', 'Blog\PoliciesController@coockiePolicy')->name('coockie-policy');
Route::get('/legal-data', 'Blog\PoliciesController@legalData')->name('legal-data');
Route::post('/blog/load_data', 'Articles\ArticlesController@load_data')->name('load_data');
//Route::post('/blog/by-topic', 'Articles\ArticlesController@getByTopic')->name('by-topic');
Auth::routes();

// Auth
Route::get('/register', 'Admin\AdminController@redirect');
Route::get('/password/reset', 'Admin\AdminController@redirect');
Route::get('/admin', 'Admin\AdminController@admin');
Route::post('/submit','Blog\SendMailController@submit')->name('send-mail');
// Admin
Route::group(['middleware'=>'auth', 'prefix'=>'admin'],function () {
    Route::resource('/pages', 'Admin\PagesController');
    Route::resource('/articles', 'Admin\ArticlesController');
    Route::resource('/topics', 'Admin\TopicsController');
    Route::post('/pages/{page}/set-main-page', 'Admin\PagesController@setMainPage')->name('set-main-page');
});

resources/views/admin/pages/create.blade.php
@extends('layouts.admin-app')

@section('content')
<form method="post" action="{{route('pages.store')}}">
    @csrf
    <div class="form-group">
        <label for="exampleFormControlInput1">Page title</label>
        <input class="form-control" name="title" type="text" placeholder="Page title" required>
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Slug</label>
        <input class="form-control" name="slug" type="text" placeholder="Slug" required>
    </div>
    <div class="form-group">
        <div class="form-check">
            <input class="form-check-input" type="checkbox" id="invalidCheck2" value="1" name="main_page">
            <label class="form-check-label" for="invalidCheck2">
                Make it main page?
            </label>
        </div>
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Page parrent</label>
        <select class="form-control" name="parent_id">
            <option value="0">None</option>
            @foreach($pages as $page)
            <option value="{{$page->id}}">{{$page->title}}</option>
            @endforeach
        </select>
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Post</label>
        <textarea class="form-control post" id="exampleFormControlTextarea1" name="post" rows="5"></textarea>
    </div>
    <a href="{{route('pages.index')}}" class="btn btn-secondary">Back</a>
    <button type="submit" class="btn btn-success">Create</button>
</form>
@endsection

resources/views/admin/pages/edit.blade.php
@extends('layouts.admin-app')

@section('content')
    <form method="post" action="{{route('pages.update', $page->id)}}">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="exampleFormControlInput1">Page title</label>
            <input class="form-control" name="title" type="text" placeholder="Page title" value="{{$page->title}}" required>
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Slug</label>
            <input class="form-control" name="slug" type="text" placeholder="Slug" value="{{$page->slug}}" id="slug" required>
        </div>
        <div class="form-group">
            <div class="form-check">
                @if($page->main_page === 1)
                    <input class="form-check-input" type="checkbox" id="invalidCheck2" value="1" name="main_page" checked>
                    @else
                    <input class="form-check-input" type="checkbox" id="invalidCheck2" value="1" name="main_page">
                    @endif
                <label class="form-check-label" for="invalidCheck2">
                    Make it main page?
                </label>
            </div>
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Page parrent</label>
            @if($page->children()->count())
                <p class="warning">
                    Sorry, you cannot select the parent page for the parent page.
                </p>
            @else
            <select class="form-control" name="parent_id">
                <option value="0">None</option>
                @foreach($pages as $item)
                    @if($page->parent_id == $item->id)
                        <option value="{{$item->id}}" selected>{{$item->title}}</option>
                    @else
                        @if($page->id == $item->id)
                        @else
                        <option value="{{$item->id}}">{{$item->title}}</option>
                        @endif
                    @endif
                @endforeach
            </select>
            @endif
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Post</label>
            <textarea class="form-control editor" id="exampleFormControlTextarea1" name="post" rows="5">{!!$page->post!!}</textarea>
        </div>
        <a href="{{route('pages.index')}}" class="btn btn-secondary">Back</a>
        <button type="submit" class="btn btn-success">Save</button>
    </form>
@endsection

resources/views/admin/pages/index.blade.php
@extends('layouts.admin-app')

@section('content')
    <a href="{{route('pages.create')}}" class="btn btn-info mb-1 w-100">Create page</a>
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Page title</th>
            <th scope="col">Page url</th>
            <th scope="col">Subpages</th>
            <th scope="col">Main page</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach($pages as $key => $value)
        <tr class="admin-table">
            <th scope="row">{{$key+1}}</th>
            <td>{{$value->title}}</td>
            <td>{{$value->slug}}</td>
            <td>
                @if($value->parent_id == 0)
                @if($value->children()->count())
                <ul class="subpage-table">
                    @foreach($value->children() as $children)
                    <li><a href="/page/{{$children->slug}}">{{$children->title}}</a></li>
                    @endforeach
                </ul>
                @else
                    <p style="color: #ff6a00;">This is parent page without subpages</p>
                @endif
                @else
                    <p style="color: green">This page is a sub page of
                        @foreach($value->parents() as $parent)
                            <a href="/page/{{$parent->slug}}">{{$parent->title}}</a>
                        @endforeach
                    </p>
                @endif
            </td>
            <td class="text-center">
                @if($value->main_page)
                    <i class="fa fa-check check"></i>
                    @else
                @endif
            </td>
            <td class="d-flex">
                <a class="btn btn-warning action-button" href="{{route('pages.edit', $value->id)}}">Edit</a>
                @if($value->main_page === 1)

                @else
                    <form method="post" action="{{route('set-main-page', $value->id)}}">
                        @csrf
                        @method('post')
                        <button class="btn btn-success action-button ml-2" type="submit">Main page</button>
                    </form>
                @endif
                <form method="post" action="{{route('pages.destroy', $value->id)}}">
                    @csrf
                    @method('delete')
                    <button class="btn btn-danger action-button ml-2" type="submit">Delete</button>
                </form>

            </td>
{{--            <td></td>--}}
        </tr>
        @endforeach
        </tbody>
    </table>
@endsection