routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Site
Route::get('/', 'Blog\BlogController@index');
Route::get('/page/{slug}', 'Blog\BlogController@show')->name('page');
Route::resource('/blog','Articles\ArticlesController');
//Route::get('/blog/topic/{slug}', 'Articles\ArticlesController@showBySlug')->name('show-by-slug');
//Route::post('/blog/topic/{slug}', 'Articles\ArticlesController@loadBySlug')->name('show-by-slug-topic');
Route::get('/coockie-policy', 'Blog\PoliciesController@coockiePolicy')->name('coockie-policy');
Route::get('/legal-data', 'Blog\PoliciesController@legalData')->name('legal-data');
Route::post('/blog/load_data', 'Articles\ArticlesController@load_data')->name('load_data');
//Route::post('/blog/by-topic', 'Articles\ArticlesController@getByTopic')->name('by-topic');
Auth::routes();

// Auth
Route::get('/register', 'Admin\AdminController@redirect');
Route::get('/password/reset', 'Admin\AdminController@redirect');
Route::get('/admin', 'Admin\AdminController@admin');
Route::post('/submit','Blog\SendMailController@submit')->name('send-mail');
// Admin
Route::group(['middleware'=>'auth', 'prefix'=>'admin'],function () {
    Route::resource('/pages', 'Admin\PagesController');
    Route::resource('/articles', 'Admin\ArticlesController');
    Route::resource('/topics', 'Admin\TopicsController');
    Route::post('/pages/{page}/set-main-page', 'Admin\PagesController@setMainPage')->name('set-main-page');
});

resources/views/admin/components/admin-nav.blade.php
<nav>
    <div class="admin-menu-item">
        <a href="{{route('pages.index')}}">
            PAGES
        </a>
    </div>
    <div class="admin-menu-item">
        <a href="{{route('articles.index')}}">
            ARTICLES
        </a>
    </div>
    <div class="admin-menu-item">
        <a href="{{route('topics.index')}}">
            TOPICS
        </a>
    </div>
    <div class="admin-menu-item">
        <a href="/">
            MAIN PAGE
        </a>
    </div>
</nav>

resources/views/admin/components/flash-messages.blade.php
@if ($message = Session::get('success'))
    <div id="alert-admin" style="text-align: center" class="alert alert-success alert-dismissible fade show" role="alert">
{{--        <button type="button" class="close" data-dismiss="alert">×</button>--}}
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('error'))
    <div id="alert-admin" style="text-align: center" class="alert alert-danger alert-dismissible fade show" role="alert">
{{--        <button type="button" style="text-align: center;" class="close" data-dismiss="alert">×</button>--}}
        <strong>{{ $message }}</strong>
    </div>

@endif

@if ($message = Session::get('warning'))
    <div id="alert-admin" class="alert alert-warning alert-dismissible fade show" role="alert">
{{--        <button type="button" class="close" data-dismiss="alert">×</button>--}}
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('info'))
    <div id="alert-admin" class="alert alert-info alert-dismissible fade show" role="alert">
{{--        <button type="button" class="close" data-dismiss="alert">×</button>--}}
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($errors->any())
    @foreach ($errors->all() as $error)
{{--        <div id="my-alert" class="alert alert-danger alert-dismissible fade show" role="alert">--}}
        <div class="alert alert-danger alert-dismissible fade show" style="text-align: center" id="alert-admin">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>{{ $error }}</strong>
        </div>
    @endforeach
@endif

resources/views/admin/components/head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<title>{{ config('app.name', 'Laravel') }}</title>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}" defer></script>
<script src="{{ asset('js/jquery.min.js') }}"></script>
<script src="{{ asset('js/tinymce/tinymce.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js"></script>

<!-- Fonts -->
<link rel="dns-prefetch" href="//fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

<!-- Styles -->
<link href="{{ asset('css/app.css') }}" rel="stylesheet">

resources/views/admin/components/scripts.blade.php
<script type="text/javascript">
    tinymce.init({
        selector : "textarea",
        height: 500,
        plugins : ["advlist autolink lists link image charmap print preview anchor", "searchreplace visualblocks code fullscreen", "textcolor", "insertdatetime media table contextmenu paste jbimages"],
        toolbar : "insertfile undo redo | styleselect | bold italic strikethrough  forecolor backcolor | fontsizeselect | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | jbimages",
        relative_urls: false
    });
</script>
{{--"insertdatetime media table contextmenu paste jbimages"--}}
<!--jbimage-->
<script>
    $(function(){
        window.setTimeout(function(){
            $('#alert-admin').alert('close');
        },3000);
    });
</script>